module.exports = {
  internetConnectionError: 'The Internet connection appears to be offline.',
  emailRequire: 'Please enter your email address',
  validEmail: 'Email format invalid.',
  passwordRequire: 'Please enter your password',
  validpassword: 'password must be 8 character and include 0-9, a-z, A-Z',
  termsAndConition:
    'By tapping Sign in, or Continue with Google, Telegram, or Twitter, you agree to AppNames',
  term: ' Terms of Use',
  and: ' and ',
  privacy: 'Privacy Policy.',
  loginWithEmail: 'Log in with email',
  forgotPassword: 'Forgot your password?',
  or: 'or',
  loginWithGoogle: 'Continue with Google',
  loginWithTelegram: 'Continue with Telegram',
  loginWithTwitter: 'Continue with Twitter',
  dontHaveAccount: 'Don’t have an account? ',
  signUp: 'Sign up',
  email: 'Email address',
  password: 'Password',
  nickName: 'Nickname',
  confirmPassword: 'Confirm Password',
  nickNameTerms:
    'The nickname can contain only letters a-z, numbers and certain special characters.',
  register: 'Register',
  nameRequire: 'Please enter nick name',
  emailverify: 'An email to reset your password will be sent to you.',
  confirmButton: 'Confirm',
  passwordRecovery: 'Password Recovery',
  passwordRecoveryMsg:
    'A link to reset your password has been sent to your email.',
  popupButtonTxt: 'Confirm',
  referralCode: 'Referral Code',
  refferalPlaceholder: 'Enter the referral code (if there is one)',
  confirmPasswordErr: 'please enter confirm password',
  passwrodMatchErr: 'confirm password did not match',
  skipButton: 'Skip',
  addPhoneNumber: 'Add phone number',
  phoneNumberPlaceholder: '00 0000 0000',
  phoneNumber: 'phone number',
  verificationCode: 'Enter the verification code',
  english: 'English',
  reply: 'Reply',
  writemessage: 'Write a message...',
  //Language
  language: 'Language',
  german: 'German',
};
